export const COUNTRY_CODES = [
  { code: '+91', name: 'India' },
  { code: '+1', name: 'USA/Canada' },
  { code: '+44', name: 'UK' },
  { code: '+61', name: 'Australia' },
  { code: '+81', name: 'Japan' },
  { code: '+86', name: 'China' },
  { code: '+49', name: 'Germany' },
  { code: '+33', name: 'France' },
  { code: '+39', name: 'Italy' },
  { code: '+7', name: 'Russia' },
  { code: '+55', name: 'Brazil' },
  { code: '+27', name: 'South Africa' },
  { code: '+34', name: 'Spain' },
  { code: '+65', name: 'Singapore' },
  { code: '+971', name: 'UAE' },
  { code: '+966', name: 'Saudi Arabia' },
  { code: '+60', name: 'Malaysia' },
  { code: '+64', name: 'New Zealand' },
  { code: '+82', name: 'South Korea' },
  { code: '+52', name: 'Mexico' },
  { code: '+31', name: 'Netherlands' },
  { code: '+46', name: 'Sweden' },
  { code: '+41', name: 'Switzerland' },
  { code: '+47', name: 'Norway' },
  { code: '+45', name: 'Denmark' },
  { code: '+358', name: 'Finland' },
  { code: '+353', name: 'Ireland' },
  { code: '+32', name: 'Belgium' },
  { code: '+43', name: 'Austria' },
  { code: '+48', name: 'Poland' },
  { code: '+351', name: 'Portugal' },
  { code: '+30', name: 'Greece' },
  { code: '+90', name: 'Turkey' },
  { code: '+20', name: 'Egypt' },
  { code: '+234', name: 'Nigeria' },
  { code: '+254', name: 'Kenya' },
  { code: '+54', name: 'Argentina' },
  { code: '+56', name: 'Chile' },
  { code: '+57', name: 'Colombia' },
  { code: '+51', name: 'Peru' },
  { code: '+58', name: 'Venezuela' },
  { code: '+62', name: 'Indonesia' },
  { code: '+63', name: 'Philippines' },
  { code: '+66', name: 'Thailand' },
  { code: '+84', name: 'Vietnam' },
  { code: '+92', name: 'Pakistan' },
  { code: '+880', name: 'Bangladesh' },
  { code: '+94', name: 'Sri Lanka' },
  { code: '+977', name: 'Nepal' },
  { code: '+93', name: 'Afghanistan' },
  { code: '+98', name: 'Iran' },
  { code: '+964', name: 'Iraq' },
  { code: '+963', name: 'Syria' },
  { code: '+961', name: 'Lebanon' },
  { code: '+962', name: 'Jordan' },
  { code: '+965', name: 'Kuwait' },
  { code: '+974', name: 'Qatar' },
  { code: '+973', name: 'Bahrain' },
  { code: '+968', name: 'Oman' },
  { code: '+357', name: 'Cyprus' },
  { code: '+356', name: 'Malta' },
  { code: '+354', name: 'Iceland' },
  { code: '+352', name: 'Luxembourg' },
  { code: '+377', name: 'Monaco' },
  { code: '+376', name: 'Andorra' },
  { code: '+378', name: 'San Marino' },
  { code: '+379', name: 'Vatican City' },
  { code: '+423', name: 'Liechtenstein' },
  { code: '+212', name: 'Morocco' },
  { code: '+213', name: 'Algeria' },
  { code: '+216', name: 'Tunisia' },
  { code: '+218', name: 'Libya' },
  { code: '+249', name: 'Sudan' },
  { code: '+211', name: 'South Sudan' },
  { code: '+251', name: 'Ethiopia' },
  { code: '+252', name: 'Somalia' },
  { code: '+253', name: 'Djibouti' },
  { code: '+291', name: 'Eritrea' },
  { code: '+221', name: 'Senegal' },
  { code: '+220', name: 'Gambia' },
  { code: '+224', name: 'Guinea' },
  { code: '+245', name: 'Guinea-Bissau' },
  { code: '+232', name: 'Sierra Leone' },
  { code: '+231', name: 'Liberia' },
  { code: '+225', name: 'Ivory Coast' },
  { code: '+233', name: 'Ghana' },
  { code: '+228', name: 'Togo' },
  { code: '+229', name: 'Benin' },
  { code: '+227', name: 'Niger' },
  { code: '+226', name: 'Burkina Faso' },
  { code: '+223', name: 'Mali' },
  { code: '+222', name: 'Mauritania' },
  { code: '+237', name: 'Cameroon' },
  { code: '+235', name: 'Chad' },
  { code: '+236', name: 'Central African Republic' },
  { code: '+240', name: 'Equatorial Guinea' },
  { code: '+241', name: 'Gabon' },
  { code: '+242', name: 'Congo' },
  { code: '+243', name: 'DR Congo' },
  { code: '+244', name: 'Angola' },
  { code: '+264', name: 'Namibia' },
  { code: '+267', name: 'Botswana' },
  { code: '+268', name: 'Eswatini' },
  { code: '+266', name: 'Lesotho' },
  { code: '+261', name: 'Madagascar' },
  { code: '+265', name: 'Malawi' },
  { code: '+258', name: 'Mozambique' },
  { code: '+260', name: 'Zambia' },
  { code: '+263', name: 'Zimbabwe' },
  { code: '+250', name: 'Rwanda' },
  { code: '+257', name: 'Burundi' },
  { code: '+256', name: 'Uganda' },
  { code: '+255', name: 'Tanzania' },
  { code: '+248', name: 'Seychelles' },
  { code: '+230', name: 'Mauritius' },
  { code: '+269', name: 'Comoros' },
  { code: '+593', name: 'Ecuador' },
  { code: '+591', name: 'Bolivia' },
  { code: '+595', name: 'Paraguay' },
  { code: '+598', name: 'Uruguay' },
  { code: '+501', name: 'Belize' },
  { code: '+502', name: 'Guatemala' },
  { code: '+503', name: 'El Salvador' },
  { code: '+504', name: 'Honduras' },
  { code: '+505', name: 'Nicaragua' },
  { code: '+506', name: 'Costa Rica' },
  { code: '+507', name: 'Panama' },
  { code: '+53', name: 'Cuba' },
  { code: '+509', name: 'Haiti' },
  { code: '+1809', name: 'Dominican Republic' },
  { code: '+1876', name: 'Jamaica' },
  { code: '+1868', name: 'Trinidad and Tobago' },
  { code: '+592', name: 'Guyana' },
  { code: '+597', name: 'Suriname' },
  { code: '+594', name: 'French Guiana' },
  { code: '+500', name: 'Falkland Islands' },
  { code: '+995', name: 'Georgia' },
  { code: '+374', name: 'Armenia' },
  { code: '+994', name: 'Azerbaijan' },
  { code: '+7', name: 'Kazakhstan' },
  { code: '+998', name: 'Uzbekistan' },
  { code: '+993', name: 'Turkmenistan' },
  { code: '+992', name: 'Tajikistan' },
  { code: '+996', name: 'Kyrgyzstan' },
  { code: '+976', name: 'Mongolia' },
  { code: '+852', name: 'Hong Kong' },
  { code: '+853', name: 'Macau' },
  { code: '+886', name: 'Taiwan' },
  { code: '+850', name: 'North Korea' },
  { code: '+380', name: 'Ukraine' },
  { code: '+375', name: 'Belarus' },
  { code: '+373', name: 'Moldova' },
  { code: '+40', name: 'Romania' },
  { code: '+359', name: 'Bulgaria' },
  { code: '+381', name: 'Serbia' },
  { code: '+385', name: 'Croatia' },
  { code: '+387', name: 'Bosnia and Herzegovina' },
  { code: '+382', name: 'Montenegro' },
  { code: '+383', name: 'Kosovo' },
  { code: '+389', name: 'North Macedonia' },
  { code: '+355', name: 'Albania' },
  { code: '+370', name: 'Lithuania' },
  { code: '+371', name: 'Latvia' },
  { code: '+372', name: 'Estonia' },
  { code: '+420', name: 'Czechia' },
  { code: '+421', name: 'Slovakia' },
  { code: '+36', name: 'Hungary' },
  { code: '+386', name: 'Slovenia' },
].sort((a, b) => a.name.localeCompare(b.name));
